baseURL = "https://545659928.github.io/jialongli/"
languageCode = "en-us"
title = "Jialong Li"
enableRobotsTXT = true

[params]
  author = "Jialong Li"
  name = "Jialong Li"
  role = "Assistant Professor, Waseda University"
  role2 = "Research Associate, Institute of Science Tokyo"
  location = "Tokyo, Japan"
  organization = "Waseda University / Institute of Science Tokyo"
  email = "lijialong [at] fuji [dot] waseda [dot] jp"
  scholar = "https://scholar.google.com/citations?user=EUqTNVcAAAAJ&hl=en"
  researchmap = "https://researchmap.jp/jialong?lang=en"
  researchgate = "https://www.researchgate.net/profile/Jialong-Li"
  linkedin = "https://www.linkedin.com/in/jialong-li-ba592615b/"
  map = "https://www.waseda.jp/inst/gcs/en/access/"
  address = "Green Computing Systems Research and Development Center, Wasedamachi-27, Shinjuku-ku, Tokyo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menu.main]]
    name = "Research"
    pageRef = "/research"
    weight = 20
  [[menu.main]]
    name = "Publications"
    pageRef = "/publications"
    weight = 30
  [[menu.main]]
    name = "CV"
    pageRef = "/cv"
    weight = 40
  [[menu.main]]
    name = "日本語"
    pageRef = "/jp"
    weight = 50
